package com.Assistant.Email.Service;

import java.time.Duration;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import com.Assistant.Email.EmailType.EmailRequest;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class EmailService {

    private final WebClient webClient;
    private final String apiKey;

    public EmailService(WebClient.Builder webClientBuilder,
            @Value("${gemini.api.url}") String BaseUrl,
            @Value("${gemini.api.key}") String GeminiApiKey) {
        this.apiKey = GeminiApiKey;
        this.webClient = webClientBuilder.baseUrl(BaseUrl)
                .build();
    }

    public String generateEmailReply(EmailRequest emailRequest) {

        // STEP : 1: Now We will Build Prompt,
        String prompt = buildPrompt(emailRequest);

        // Will prepare Raw JSON Body

        // Map<String, Object> RequestBody = Map.of(
        // "contents", List.of(
        // Map.of(
        // "parts", List.of(
        // Map.of("text", prompt)))));
        String RequestBody = String.format("""
                {
                    "contents": [
                        {
                            "parts": [
                                {
                                    "text": "%s"
                                }
                            ]
                        }
                    ]
                }
                """, prompt);
        // Send Request

        String response = webClient.post()
                .uri(uriBuilder -> uriBuilder
                        .path("/models/gemini-2.5-flash:generateContent")
                        .build())

                .accept(MediaType.APPLICATION_JSON)
                .header("x-goog-api-key", apiKey)
                .header("Content-Type", "application/json")
                .bodyValue(RequestBody)
                .retrieve()
                .onStatus(
                        status -> status.value() == 503,
                        clientResponse -> clientResponse
                                .bodyToMono(String.class)
                                .map(body -> new RuntimeException("Gemini API temporarily unavailable")))
                .bodyToMono(String.class)
                .retryWhen(
                        reactor.util.retry.Retry.fixedDelay(3, Duration.ofSeconds(2)))
                .block();
        // Extract Important Response

        return extractResponseContent(response);

    }

    private String extractResponseContent(String response) {

        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(response);

            // 🔴 ERROR CASE 1: Gemini error response
            if (root.has("error")) {
                return "Gemini API Error: " + root.path("error").path("message").asText();
            }

            // 🔴 ERROR CASE 2: No candidates returned
            JsonNode candidates = root.path("candidates");
            if (!candidates.isArray() || candidates.isEmpty()) {
                return "No response generated by Gemini (candidates empty)";
            }

            JsonNode firstCandidate = candidates.get(0);
            if (firstCandidate == null) {
                return "Gemini returned null candidate";
            }

            JsonNode parts = firstCandidate
                    .path("content")
                    .path("parts");

            if (!parts.isArray() || parts.isEmpty()) {
                return "Gemini response has no text parts";
            }

            // return root.path("candidates")
            // return candidates.get(0)
            // .path("content")
            // // .get(0)
            // .path("parts")
            return parts.get(0)
                    .path("text")
                    .asText();
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    private String buildPrompt(EmailRequest emailRequest) {
        StringBuilder prompt = new StringBuilder();
        prompt.append("Generate a Professional email reply without subject line for the following email : ");

        if (emailRequest.getTone() != null && !emailRequest.getTone().isEmpty()) {
            prompt.append("Use a ").append(emailRequest.getTone()).append("tone.");
        }

        prompt.append("Origional Email : \n").append(emailRequest.getEmailContent());

        return prompt.toString();
    }

}
